Redis for token cache
sanyadevgon/assignment pull request #3
Opened 2020-08-11 05:53 UTC by sanyadevgon

2020-08-17 07:22 UTC, sumitmundraoyo commented on src/main/java/com/company/managementservice/ManagementServiceApplication.java
> +	/*@Bean
We can loose commented code here

2020-08-18 12:49 UTC, sumitmundraoyo requested changes

2020-08-18 12:49 UTC, sumitmundraoyo commented on src/main/java/com/company/managementservice/controller/DepartmentController.java
> +        if (bindingResult.hasErrors()) {
Are we doing anything custom than library for field errors, if not, we can go with default spring implementations for @Valid annotations too.

2020-08-18 12:49 UTC, sumitmundraoyo commented on src/main/java/com/company/managementservice/controller/DepartmentController.java
> +        log.info("DepartmentController : putDepartmentDetails : Received Request to put Department Details for id:{}",
https://www.baeldung.com/spring-validate-requestparam-pathvariable
try out validation annotation, reduces code bloating.
DRY( do not repeat yourself ) :)

2020-08-18 12:49 UTC, sumitmundraoyo commented on src/main/java/com/company/managementservice/controller/DepartmentController.java
> +        log.info("DepartmentController : removeDepartmentDetails : Received Request to remove Department Details :{}",
Do we have a request interceptor for logging in application? We can use just that to log info level details of each request. The class and method name does not provide any information, and we can anyway have that with logger context. If method refactoring is done, these method names are often left out in logs, leading to confusion. A good practice is not to put in these details at all. Let the library take care of it.

2020-08-18 12:49 UTC, sumitmundraoyo commented on src/main/java/com/company/managementservice/controller/EmployeeController.java
> +    public ServiceResponse<?> saveEmployeeDetails(@Valid @RequestBody EmployeeDto employeeDto,
Please use a specific type instead of <?> in all controller mappings method. Type strictness remains only with that. If there is a dto being returned from a controller endpoint, we can list those controller methods just with a search usage directly, but here, we loose type safety and usage control.

2020-08-18 12:49 UTC, sumitmundraoyo commented on src/main/java/com/company/managementservice/controller/SalaryController.java
> +    @GetMapping(value = "/{employeeId}/details")
Is there a reason to add details in the path? is there a separate /{id} endpoint with lesser/different details than this one? Restful APIs are easier to integrate and extend when needed.

2020-08-18 12:49 UTC, sumitmundraoyo commented on src/main/java/com/company/managementservice/exception/ConstraintViolationException.java
> +public class ConstraintViolationException extends Exception {
where is the usage for this exception? Not in this PR?

2020-08-18 12:49 UTC, sumitmundraoyo commented on src/main/java/com/company/managementservice/controller/EmployeeController.java
> +        if (employeeId == null || departmentId == null)
first two conditions are redundant

2020-08-18 12:49 UTC, sumitmundraoyo commented on src/main/java/com/company/managementservice/controller/EmployeeController.java
> +        if (employeeId == null || departmentId == null)
spring validators should be checking nonnull, or if they are not function, they should be removed.

2020-08-18 12:49 UTC, sumitmundraoyo commented on src/main/java/com/company/managementservice/controller/OrganisationController.java
> +    public ResponseEntity<?> removeorganisation(@NonNull @PathVariable Integer id) throws NotFoundException {
lets loose the verb after id. we are not working on any nested resource here under id, right?

2020-08-18 12:49 UTC, sumitmundraoyo commented on src/main/java/com/company/managementservice/controller/OrganisationController.java
> +    public ResponseEntity<?> removeorganisation(@NonNull @PathVariable Integer id) throws NotFoundException {
most of the restful apis have actions as query param if needed.

2020-08-18 14:04 UTC, sanyadevgon commented on src/main/java/com/company/managementservice/controller/DepartmentController.java
> +        log.info("DepartmentController : putDepartmentDetails : Received Request to put Department Details for id:{}",
javax valid annotation wasnt working for null id fields with web security, so i tried all options initially, removed those redundant!

2020-08-18 14:05 UTC, sanyadevgon commented on src/main/java/com/company/managementservice/controller/EmployeeController.java
> +    public ServiceResponse<?> saveEmployeeDetails(@Valid @RequestBody EmployeeDto employeeDto,
Okay,will update

2020-08-21 17:03 UTC, closed without merging