Kafka changes and currency converter
sanyadevgon/assignment pull request #4
Opened 2020-08-21 08:46 UTC by sanyadevgon

2020-08-21 15:31 UTC, rahul-400 commented on src/main/java/com/company/managementservice/controller/EmployeeController.java
>      @DeleteMapping("/{employeeId}/terminate")
I think we don't need terminate at the end of the url. /employeeId with delete mapping will work

2020-08-21 15:35 UTC, rahul-400 commented on src/main/java/com/company/managementservice/controller/SalaryController.java
> +                                                                                  @NonNull @PathVariable Integer organisationId)
How are you handling the case if increment and currency passed in url is null?

2020-08-21 15:36 UTC, rahul-400 commented on src/main/java/com/company/managementservice/controller/SalaryController.java
>                          "Salary Updated Successfully ",
Better declare all this strings as string constants. Apply it all the places wherever applicable

2020-08-21 15:41 UTC, rahul-400 commented on src/main/java/com/company/managementservice/model/dto/SalaryDto.java
in which format from_date and to_date is stored in db, is it yyyy-mm-dd or yyyy-mm-dd with times?

2020-08-21 15:49 UTC, rahul-400 commented on src/main/java/com/company/managementservice/service/SalaryService.java
>      }
If the updating cache code is repeated twice why don't create a method for this. Don't have to write the same thing twice.

2020-08-21 15:49 UTC, rahul-400 commented on src/main/java/com/company/managementservice/service/SalaryService.java
>          }
Same goes here, better create a different method and call those method here.

2020-08-21 15:51 UTC, rahul-400 commented on src/main/java/com/company/managementservice/service/SalaryService.java
>          Long employeeId = kafkaDto.getId();
Possible NPE.

2020-08-21 15:56 UTC, rahul-400 commented on src/main/java/com/company/managementservice/controller/DepartmentController.java
>      @PutMapping(value = "/{departmentId}/assign-organisation/{organisationId}")
deprtmentId in url should come after oganisationId. Basically an organisation is the owner of a department right?

2020-08-21 15:59 UTC, rahul-400 commented on src/main/java/com/company/managementservice/controller/EmployeeController.java
>      @DeleteMapping(value = "/{employeeId}/remove-from-department/{departmentId}")
can't this url be like departmentId/employeeId/remove. Two things:
1) If we do not mention remove, still I guess it might work. 
2) Employee is part of a department, so latter should come first in url and former should come later

2020-08-21 16:08 UTC, rahul-400 commented on src/test/java/com/company/managementservice/service/SalaryServiceTest.java
> +    }
If you use @RunWith(MockitoJUnitRunner.class) then we don't have to write this code of initialising mockito annotations. MockitoJUnitRunner does that for us.

2020-08-21 16:10 UTC, rahul-400 commented on src/test/java/com/company/managementservice/service/SalaryServiceTest.java
> +
Why this method is throwing NotFoundException, didn't get it. Do we need NotFoundException here?

2020-08-21 16:12 UTC, rahul-400 commented on src/test/java/com/company/managementservice/service/SalaryServiceTest.java
> +
If you have mentioned in @Test annotation the type of exception it will throw then there's no need of adding NotFoundException. Basically this test is testing that this particular scenario will throw NotFoundException for that @Test its specified. So you don't need it again with the method.

2020-08-21 16:14 UTC, rahul-400 commented on src/test/java/com/company/managementservice/service/SalaryServiceTest.java
> +    public void updateSalaryByDepartmentShouldThrowExceptionForNullInc() throws NotFoundException, MethodArgumentNotValidException{
Same goes here, and for all the tests. We don't need throws attached to method.

2020-08-21 16:18 UTC, rahul-400 commented on src/test/java/com/company/managementservice/service/SalaryServiceTest.java
> +        Department department = new Department();
Test name should tell what exactly we are testing, way of writing test name which makes things more clear to the reader: test_condition_for_which_you_are_testing_name_of_the_method_success/fail()
This will make easy for reader to know what condition exactly we are testing and what methods is tested and the result we should expect.

2020-08-21 16:22 UTC, rahul-400 requested changes
Look into test method name once again. Its quite difficult to make out what conditions we are testing.

2020-08-21 16:24 UTC, rahul-400 commented on src/test/java/com/company/managementservice/service/SalaryServiceTest.java
> +    }
Also read about MockitoJunitRunner and @InjectMocks

2020-08-21 16:58 UTC, sumitmundraoyo requested changes

2020-08-21 16:58 UTC, sumitmundraoyo commented on src/main/java/com/company/managementservice/configuration/AuthorizationServerConfig.java
> +                .accessTokenValiditySeconds(3000)
could be kept as a class constant or application property.

2020-08-21 16:58 UTC, sumitmundraoyo commented on src/main/java/com/company/managementservice/constant/Constants.java
> +    public static final String GROUP_ID="group2";
group id value decides which of the listeners receive a message from a partition of a topic. read more on group name strategy, it is important in a clustered deployment

2020-08-21 16:58 UTC, sumitmundraoyo commented on src/main/java/com/company/managementservice/controller/EmployeeController.java
>      @DeleteMapping("/{employeeId}/terminate")
can also drop terminate from url to make it a completely RESTful url convention.

2020-08-21 16:58 UTC, sumitmundraoyo commented on src/main/java/com/company/managementservice/controller/SalaryController.java
> +    @PutMapping(value = "/absolute/{increment}/{currency}/update-by-department/{departmentId}")
we can also make currency part of request body instead of path variable. Also try to come up with a good url naming scheme here.

2020-08-21 16:58 UTC, sumitmundraoyo commented on src/main/java/com/company/managementservice/controller/SalaryController.java
> +    @PutMapping(value = "/absolute/{increment}/{currency}/update-by-department/{departmentId}")
absolute and percentage should also be part of request body as a mode of increment. Try to unify two method controller endpoints and come up with a request body to cater both. The endpoint purpose is same for both ie. update department salary.

2020-08-21 16:58 UTC, sumitmundraoyo commented on src/main/java/com/company/managementservice/model/dto/KafkaDto.java
> +    @Min(value = 18)
It would be interesting to see how spring confirms validations on a kafka message here. If there are message errors, be sure to handle error scenarios as well as kafka would need an ack for message processing and offset mangement.

2020-08-21 16:58 UTC, sumitmundraoyo commented on src/main/java/com/company/managementservice/model/entity/AbstractEntity.java
> +    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
can try keeping this date pattern as a class constant and refer everywhere in dto as well as entity if needed

2020-08-21 16:58 UTC, sumitmundraoyo commented on src/main/java/com/company/managementservice/model/enums/CurrencyType.java
> +    public final Long Rupeevalue;
missed variable naming convention.

2020-08-21 16:58 UTC, sumitmundraoyo commented on src/main/java/com/company/managementservice/model/enums/CurrencyType.java
> +    public final Long Rupeevalue;
can also make this a private field with a public getter. Trick question: Should we keep a setter for this value?

2020-08-21 16:58 UTC, sumitmundraoyo commented on src/main/java/com/company/managementservice/repo/OrganisationRepo.java
>      Optional<Department> findById(Long organisationId);
should the return type not a "Optional Organisation" object ?

2020-08-21 16:58 UTC, sumitmundraoyo commented on src/main/java/com/company/managementservice/service/SalaryService.java
> +    CurrencyConvertorService currencyConvertorService;
this looks like a static class use-case then a injected bean. see if it can be made a static class reference.

2020-08-21 16:58 UTC, sumitmundraoyo commented on src/main/java/com/company/managementservice/service/SalaryService.java
> +        return modelMapper.map(salary, SalaryDto.class);
need a transactional annotation on this method, I see multiple db update queries going on. Also, why employee needs an update? Are we saving any association in employee table too?

2020-08-21 16:58 UTC, sumitmundraoyo commented on src/main/java/com/company/managementservice/service/SalaryService.java
>          salary.setFromDate(LocalDate.now());
again, cascaded save in this method. I hope this is being done wrapped in a transaction

2020-08-21 16:58 UTC, sumitmundraoyo commented on src/main/java/com/company/managementservice/service/SalaryService.java
>          salary.setFromDate(LocalDate.now());
Please read more about hibernate orm. How does it propogates or rollbacks a transaction. Also read about entities lazy and eager fetch for associations.

2020-08-21 16:58 UTC, sumitmundraoyo commented on src/main/java/com/company/managementservice/service/SalaryService.java
> +            throw new MethodArgumentNotValidException("Percent not in range 0 to 100,-100 to 0 ");
why is there an upper limit of 100 to the percentage?

2020-08-21 16:58 UTC, sumitmundraoyo commented on src/main/java/com/company/managementservice/service/SalaryService.java
> +            salary.setCurrency("RUPEES");
must use enum as defined earlier in a currency class

2020-08-21 16:58 UTC, sumitmundraoyo commented on src/main/java/com/company/managementservice/service/SalaryService.java
> +            salary.setCurrency("RUPEES");
enum usaged

2020-08-21 16:58 UTC, sumitmundraoyo commented on src/main/java/com/company/managementservice/service/SalaryService.java
> +            salary.setCurrency("RUPEES");
also date to timestamp conversion required for from date and end date in order to allow same day updates.

2020-08-21 16:58 UTC, sumitmundraoyo commented on src/test/java/com/company/managementservice/service/SalaryServiceTest.java
> +@RunWith(SpringRunner.class)
This is a sort of integration test. Try to write a test with MockitoJunitRunner and test against mocked repo objects. They are faster and save other bean config related issues. A unit test must have smallest scope of unit getting tested. This results in future proof reliable tests.

2020-08-21 16:58 UTC, sumitmundraoyo commented on src/test/java/com/company/managementservice/service/SalaryServiceTest.java
> +@RunWith(SpringRunner.class)
@rahul-400 Please help here with mockito learning I discussed with you earlier, including test naming convention and other expected behaviors

2020-08-21 16:58 UTC, sumitmundraoyo commented on src/test/java/com/company/managementservice/service/SalaryServiceTest.java
> +    public void updateSalaryByDepartmentShouldThrowExceptionC() throws NotFoundException, MethodArgumentNotValidException {
Since we have many NotFoundException with different contextual message, I would suggest checking for the error message too.

2020-08-24 05:53 UTC, sumitmundraoyo reviewed
I reviewed some time back, some of these may not apply

2020-08-24 08:56 UTC, sanyadevgon commented on src/main/java/com/company/managementservice/service/SalaryService.java
> +        return modelMapper.map(salary, SalaryDto.class);
It is marked as Transactional, this is for salary post

2020-08-25 05:55 UTC, sanyadevgon commented on src/test/java/com/company/managementservice/service/SalaryServiceTest.java
> +
Method throws NotFound is for employee id not found, test for currentSalary throws exception when salary not found

2020-08-25 08:26 UTC, sanyadevgon commented on src/main/java/com/company/managementservice/model/enums/CurrencyType.java
> +    public final Long Rupeevalue;
no, setter wont be required since rupee value is predefined

2020-08-26 07:57 UTC, sumitmundraoyo commented on src/main/java/com/company/managementservice/controller/SalaryController.java
> +    @GetMapping(value = "/{employeeId}/salary/details")
we can even loose details word from url.

2020-08-26 07:57 UTC, sumitmundraoyo commented on src/main/java/com/company/managementservice/controller/SalaryController.java
>  public class SalaryController {
should add a base controller mapping also, or move individual apis to respective controller of department and employee. Else we would have clubbed mappings later

2020-08-28 05:26 UTC, merged